/********************************************************************
* BaccRootConverterEvent_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BaccRootConverterEvent_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBaccRootConverterEvent_dict();
extern void G__cpp_setup_inheritanceBaccRootConverterEvent_dict();
extern void G__cpp_setup_typetableBaccRootConverterEvent_dict();
extern void G__cpp_setup_memvarBaccRootConverterEvent_dict();
extern void G__cpp_setup_globalBaccRootConverterEvent_dict();
extern void G__cpp_setup_memfuncBaccRootConverterEvent_dict();
extern void G__cpp_setup_funcBaccRootConverterEvent_dict();
extern void G__set_cpp_environmentBaccRootConverterEvent_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "BaccRootConverterEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_TClass;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_TBuffer;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_TMemberInspector;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_TObject;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_string;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_volumeInfo;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_primaryParticleInfo;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_stepInfo;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_trackInfo;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEstepInfocOallocatorlEstepInfogRsPgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEstepInfocOallocatorlEstepInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_reverse_iteratorlEvectorlEstepInfocOallocatorlEstepInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_BaccRootConverterEvent;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEvolumeInfocOallocatorlEvolumeInfogRsPgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEvolumeInfocOallocatorlEvolumeInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_reverse_iteratorlEvectorlEvolumeInfocOallocatorlEvolumeInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEprimaryParticleInfocOallocatorlEprimaryParticleInfogRsPgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEprimaryParticleInfocOallocatorlEprimaryParticleInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_reverse_iteratorlEvectorlEprimaryParticleInfocOallocatorlEprimaryParticleInfogRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEtrackInfocOallocatorlEtrackInfogRsPgR;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_vectorlEtrackInfocOallocatorlEtrackInfogRsPgRcLcLiterator;
extern G__linked_taginfo G__BaccRootConverterEvent_dictLN_reverse_iteratorlEvectorlEtrackInfocOallocatorlEtrackInfogRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<stepInfo,allocator<stepInfo> > G__vectorlEstepInfocOallocatorlEstepInfogRsPgR;
typedef vector<volumeInfo,allocator<volumeInfo> > G__vectorlEvolumeInfocOallocatorlEvolumeInfogRsPgR;
typedef vector<primaryParticleInfo,allocator<primaryParticleInfo> > G__vectorlEprimaryParticleInfocOallocatorlEprimaryParticleInfogRsPgR;
typedef vector<trackInfo,allocator<trackInfo> > G__vectorlEtrackInfocOallocatorlEtrackInfogRsPgR;
